package com.example.wooclamse

data class Question(

    // When creating a new Question entity in Spring Boot, we assume that the @Id and @GeneratedValue annotations are used
    val id: Int, //auto-generated by backend
    val title: String,
    val answers: Array<String>, //array of 4 possible answers
    val correctAnswerIndex: Int //index (0-based) of correct answer
)

data class Answer(
    val questionId: Int, //ID of the question answered
    val selectedAnswerIndex: Int //ID of the answer submitted
)
